/*  ui.js

    The setup screen: the source list, the fields each source
    shows, and file loading (picker, click, drag and drop).
*/

// ==========================================================
// SETUP SCREEN
// ==========================================================
const SOURCES = {
  file: {
    label:'file  —  anything you drop in',
    desc:'Point it at any file and it works out what to do from the extension:\n'+
         '.svg is read as vectors, .csv as saved points, pictures get traced.\n'+
         'The simplest option — start here.',
    fields:[
      {k:'file',  t:'file',   label:'file'},
      {k:'n',     t:'int',    label:'points to sample', v:3000, hint:'more = finer'},
      {k:'mode',  t:'choice', label:'if it is a picture', v:'line art',
       opts:['line art','silhouette'],
       hint:'every stroke, or just the outer outline'}
    ]},
  text: {
    label:'text  —  letters',
    desc:'Any letter or word, drawn in a font and traced.\n'+
         'Each letter and hole is its own loop, so expect connector lines\n'+
         'between them — same as line art.',
    fields:[
      {k:'text',   t:'str', label:'text', v:'π', hint:'a letter, a word, a symbol'},
      {k:'font',   t:'str', label:'font', v:'sans-serif',
       hint:'sans-serif, serif, Impact, Georgia...'},
      {k:'weight', t:'choice', label:'weight', v:'bold', opts:['normal','bold'],
       hint:'bold traces more thickly'},
      {k:'n',      t:'int', label:'points to sample', v:4000,
       hint:'raise it for long words'}
    ]},
  shape: {
    label:'shape  —  built-in formula',
    desc:'A shape generated by maths — no file needed. Good for testing, and\n'+
         'for seeing how many epicycles a given shape actually needs.',
    fields:[{k:'shape', t:'shape', label:'which shape', v:'star'}]},
  image: {
    label:'image  —  line art / logo',
    desc:'Traces EVERY line in a picture, including separate letters and the\n'+
         'inside of outlined strokes. Straight connector lines will appear\n'+
         'between the pieces — a Fourier series draws one continuous loop.',
    fields:[
      {k:'file',      t:'file', label:'image file'},
      {k:'n',         t:'int',  label:'points to sample', v:4000, hint:'more = finer'},
      {k:'invert',    t:'bool', label:'shape is light on dark', v:false},
      {k:'minLen',    t:'int',  label:'ignore pieces smaller than', v:25,
       hint:'raise it to drop speckle and jpg noise'},
      {k:'maxShapes', t:'int',  label:'max separate pieces', v:40}
    ]},
  silhouette: {
    label:'silhouette  —  one solid shape',
    desc:'Traces a single outline: the edge of the biggest solid blob.\n'+
         'Use it for filled shapes. Internal detail is ignored — switch to\n'+
         '"image" if you lose lines.',
    fields:[
      {k:'file',   t:'file', label:'image file'},
      {k:'n',      t:'int',  label:'points to sample', v:2500, hint:'more = finer'},
      {k:'invert', t:'bool', label:'shape is light on dark', v:false}
    ]},
  svg: {
    label:'svg  —  vector file',
    desc:'Reads the real curves out of an .svg, so there are no pixels and no\n'+
         'jagged edges. The best option if you have one.',
    fields:[
      {k:'file', t:'file', label:'svg file'},
      {k:'n',    t:'int',  label:'points to sample', v:3000, hint:'more = finer'},
      {k:'longestOnly', t:'bool', label:'longest path only', v:false,
       hint:'off = every path, chained together'}
    ]},
  csv: {
    label:'csv  —  points you saved',
    desc:'A file of x,y numbers, one point per line.\n'+
         'Anything you save from the sketcher lands here.',
    fields:[{k:'file', t:'file', label:'csv file'}]},
  draw: {
    label:'draw  —  with the mouse',
    desc:'Sketch it yourself: drag on the canvas, then press Done.\n'+
         'Whatever you draw is closed into a loop automatically.',
    fields:[]}
};

const $ = s => document.querySelector(s);
const state = {file:null, fileName:'', values:{}, shapeParams:{}};

function field(f, host, source){
  const row = document.createElement('div');
  row.className = 'row';
  row.innerHTML = `<label>${f.label}</label>`;
  const cell = document.createElement('span');
  let input;
  if (f.t === 'bool'){
    input = document.createElement('input'); input.type = 'checkbox';
    input.checked = !!f.v;
    input.onchange = () => state.values[f.k] = input.checked;
    state.values[f.k] = !!f.v;
  } else if (f.t === 'choice' || f.t === 'shape'){
    input = document.createElement('select');
    const opts = f.t === 'shape' ? Object.keys(SHAPES) : f.opts;
    opts.forEach(o => input.add(new Option(o, o)));
    input.value = f.v;
    state.values[f.k] = f.v;
    input.onchange = () => {
      state.values[f.k] = input.value;
      if (f.t === 'shape') shapeParams(input.value);
    };
  } else if (f.t === 'file'){
    input = document.createElement('button');
    input.textContent = 'choose a file...';
    input.onclick = () => $('#fileInput').click();
  } else {
    input = document.createElement('input');
    input.type = f.t === 'int' ? 'number' : 'text';
    input.value = f.v;
    input.style.width = '100%';
    state.values[f.k] = f.v;
    input.oninput = () =>
      state.values[f.k] = f.t === 'int' ? +input.value : input.value;
  }
  cell.appendChild(input);
  row.appendChild(cell);
  const hint = document.createElement('span');
  hint.className = 'hint';
  hint.textContent = f.hint || (f.t === 'file' ? (state.fileName || 'or drop one on the page') : '');
  if (f.t === 'file') hint.id = 'fileHint';
  row.appendChild(hint);
  host.appendChild(row);
}

function shapeParams(name){
  const old = $('#shapeParams');
  if (old) old.remove();
  const box = document.createElement('div');
  box.id = 'shapeParams';
  box.style.marginTop = '10px';
  state.shapeParams = {};
  const defs = SHAPES[name];
  if (!Object.keys(defs).length){
    box.innerHTML = '<span class="hint">this one has no settings</span>';
  } else {
    for (const [k, v] of Object.entries(defs)){
      state.shapeParams[k] = v;
      const row = document.createElement('div');
      row.className = 'row';
      row.innerHTML = `<label>${k}</label>`;
      const cell = document.createElement('span');
      const inp = document.createElement('input');
      inp.type = 'number'; inp.value = v; inp.style.width = '100%';
      inp.step = Number.isInteger(v) ? 1 : 0.1;
      inp.oninput = () => state.shapeParams[k] = +inp.value;
      cell.appendChild(inp); row.appendChild(cell);
      const hint = document.createElement('span');
      hint.className = 'hint';
      hint.textContent = `${helpFor(name, k)}   (default ${v})`;
      row.appendChild(hint);
      box.appendChild(row);
    }
  }
  $('#params').appendChild(box);
}

function buildSource(){
  const key = $('#source').value;
  const src = SOURCES[key];
  $('#desc').textContent = src.desc;
  $('#params').innerHTML = '';
  state.values = {};
  src.fields.forEach(f => field(f, $('#params'), key));
  if (key === 'shape') shapeParams(state.values.shape || 'star');
  if (key === 'draw')
    $('#params').innerHTML = '<span class="hint">press Draw to open the sketch pad</span>';
  $('#err').textContent = '';
}

Object.entries(SOURCES).forEach(([k, v]) => $('#source').add(new Option(v.label, k)));
$('#source').onchange = buildSource;
buildSource();

// ---- file handling: input, click, drag and drop ----
function takeFile(file){
  if (!file) return;
  state.file = file;
  state.fileName = file.name;
  $('#fileName').textContent = 'loaded: ' + file.name;
  const hint = $('#fileHint');
  if (hint) hint.textContent = file.name;
  const ext = (file.name.split('.').pop() || '').toLowerCase();
  const cur = $('#source').value;
  const fileSources = ['file','image','silhouette','svg','csv'];
  if (!fileSources.includes(cur)){        // dropped while on shape/text/draw
    $('#source').value = 'file';
    buildSource();
    const h = $('#fileHint'); if (h) h.textContent = file.name;
  }
}
$('#fileInput').onchange = e => takeFile(e.target.files[0]);
$('#zone').onclick = () => $('#fileInput').click();
['dragenter','dragover'].forEach(ev =>
  document.addEventListener(ev, e => {
    e.preventDefault(); $('#zone').classList.add('hot');
  }));
['dragleave','drop'].forEach(ev =>
  document.addEventListener(ev, e => {
    e.preventDefault();
    if (ev === 'drop' || e.target === document.documentElement)
      $('#zone').classList.remove('hot');
  }));
document.addEventListener('drop', e => takeFile(e.dataTransfer.files[0]));
